name: Deploy site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: site
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare site
        run: |
          cd site || exit 0
          # install optional deps (no-op if none)
          npm ci --prefer-offline || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
